# Generated by Django 6.0.5 on 2026-06-06 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('football', '0002_alter_competition_options_alter_fixture_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('goleiro', 'Goleiro'), ('zagueiro', 'Zagueiro'), ('lateral', 'Lateral'), ('meia', 'Meia'), ('atacante', 'Atacante')], max_length=10)),
                ('football_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fantasy_players', to='football.player', verbose_name='Jogador Real')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('grande_defesa', 'Grande defesa'), ('jogo_sem_sofrer_gol', 'Jogo sem sofrer gol'), ('gols_sofridos', 'Gols sofridos'), ('cartao_amarelo', 'Cartão Amarelo'), ('cartao_vermelho', 'Cartão Vermelho'), ('gol', 'Gol'), ('assistencia', 'Assistência'), ('desarme', 'Desarme'), ('finalizacao_fora', 'Finalização (fora/trave)'), ('finalizacao_alvo', 'Finalização no alvo')], max_length=25)),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.fixture', verbose_name='Partida')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='scores.player')),
            ],
            options={
                'unique_together': {('player', 'event_type', 'fixture')},
            },
        ),
    ]
