# Generated by Django 6.0.6 on 2026-06-07 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_competition_options_alter_fixture_options_and_more'),
        ('scores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captain_lineups', to='football.player', verbose_name='Capitao')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_lineups', to='football.stage', verbose_name='Fase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_lineups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escalacao',
                'verbose_name_plural': 'Escalacoes',
                'ordering': ('stage__order', 'stage__name'),
                'unique_together': {('user', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='FantasyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fantasy_transfers_out', to='football.player', verbose_name='Saiu')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='scores.fantasylineup')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_transfers', to='football.stage', verbose_name='Fase')),
                ('to_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fantasy_transfers_in', to='football.player', verbose_name='Entrou')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Troca',
                'verbose_name_plural': 'Trocas',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FantasyLineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='scores.fantasylineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fantasy_lineup_entries', to='football.player', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Jogador escalado',
                'verbose_name_plural': 'Jogadores escalados',
                'ordering': ('order', 'id'),
                'unique_together': {('lineup', 'player')},
            },
        ),
    ]
