# Generated by Django 6.0.5 on 2026-06-08 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_coach'),
        ('scores', '0002_fantasylineup_fantasytransfer_fantasylineupplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasylineup',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fantasy_lineups', to='football.coach', verbose_name='Técnico'),
        ),
    ]
