# Generated by Django 6.0.5 on 2026-06-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AlterModelOptions(
            name='fixture',
            options={'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='playerstatistic',
            options={'verbose_name': 'Estatística de Jogador', 'verbose_name_plural': 'Estatísticas de Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Fase', 'verbose_name_plural': 'Fases'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Seleção', 'verbose_name_plural': 'Seleções'},
        ),
        migrations.AlterModelOptions(
            name='teamstatistic',
            options={'verbose_name': 'Estatística de Equipe', 'verbose_name_plural': 'Estatísticas de Equipes'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='external_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='ID Externo'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='season',
            field=models.IntegerField(verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='away_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Placar Visitante'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='football.team', verbose_name='Time Visitante'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='football.competition', verbose_name='Campeonato'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='external_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='ID Externo'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Placar Mandante'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='football.team', verbose_name='Time Mandante'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='kickoff_at',
            field=models.DateTimeField(verbose_name='Data/Hora do Kickoff'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='football.stage', verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estádio/Local'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='player',
            name='external_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='ID Externo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da Camisa'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.team', verbose_name='Seleção'),
        ),
        migrations.AlterField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='Assistências'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='football.fixture', verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='goals',
            field=models.IntegerField(default=0, verbose_name='Gols'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='interceptions',
            field=models.IntegerField(default=0, verbose_name='Interceptações'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='key_passes',
            field=models.IntegerField(default=0, verbose_name='Passes Decisivos'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='minutes',
            field=models.IntegerField(default=0, verbose_name='Minutos Jogados'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='passes',
            field=models.IntegerField(default=0, verbose_name='Passes'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='football.player', verbose_name='Jogador'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='red_cards',
            field=models.IntegerField(default=0, verbose_name='Cartões Vermelhos'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='shots',
            field=models.IntegerField(default=0, verbose_name='Chutes'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='shots_on_target',
            field=models.IntegerField(default=0, verbose_name='Chutes no Gol'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='tackles',
            field=models.IntegerField(default=0, verbose_name='Desarmes'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Cartões Amarelos'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='football.competition', verbose_name='Campeonato'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da Fase'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='team',
            name='external_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='ID Externo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='founded',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fundado em'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='corners',
            field=models.IntegerField(default=0, verbose_name='Escanteios'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_statistics', to='football.fixture', verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='fouls',
            field=models.IntegerField(default=0, verbose_name='Faltas'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='offsides',
            field=models.IntegerField(default=0, verbose_name='Impedimentos'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='possession',
            field=models.IntegerField(default=0, verbose_name='Posse de Bola (%)'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='red_cards',
            field=models.IntegerField(default=0, verbose_name='Cartões Vermelhos'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='shots',
            field=models.IntegerField(default=0, verbose_name='Chutes Totais'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='shots_on_target',
            field=models.IntegerField(default=0, verbose_name='Chutes no Alvo'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='football.team', verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='teamstatistic',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Cartões Amarelos'),
        ),
    ]
