# Generated by Django 6.0.5 on 2026-06-08 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_competition_options_alter_fixture_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID Externo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nacionalidade')),
                ('photo', models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='football.team', verbose_name='Seleção')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
    ]
